### ISSUE TITLE
Storage pool not found error

### ISSUE THREAD

**Issue by git4liluo** [pubstack/pubstack.github.io#75]
Hello, this is the error I tried but failed to avoid, when creating VM def for the bootstrap node, I got below about no storage pool with matching name 'default'. Appreciate your input!

TASK [../../roles/kubeinit_libvirt : Create VM definition for the bootstrap nodes] *******************************************************************************
skipping: [hypervisor-01] => (item=okd-master-01)  => {"ansible_loop_var": "item", "changed": false, "item": "okd-master-01", "skip_reason": "Conditional result was False"}
skipping: [hypervisor-01] => (item=okd-worker-01)  => {"ansible_loop_var": "item", "changed": false, "item": "okd-worker-01", "skip_reason": "Conditional result was False"}
failed: [hypervisor-01] (item=okd-bootstrap-01) => {"ansible_loop_var": "item", "changed": false, "cmd": "# If you use the kernel args to deploy the machine\n# Is not possible to render the template as --print-xml > vm.xml\n# If so then is good to have it like 'virsh define vm.xml'\nkernel_args='ip=dhcp rd.neednet=1 console=tty0 console=ttyS0 coreos.inst.stream=stable coreos.inst.install_dev=/dev/vda coreos.inst.image_url=http://10.0.0.100:8080/okd4/fedora-coreos-32.20200715.3.0-metal.x86_64.raw.xz coreos.inst.ignition_url=http://10.0.0.100:8080/okd4/bootstrap.ign'\nvirt-install    --connect qemu:///system    --name=okd-bootstrap-01    --memory memory=16384    --cpuset=auto    --vcpus=8,maxvcpus=16    --os-type=linux    --os-variant=fedora29    --autostart                    --network network=kimgtnet0,mac=52:54:00:6e:4d:a3,model=virtio              --disk size=20,readonly=false    --location /var/lib/libvirt/images/    --extra-args \"${kernel_args}\"\n", "delta": "0:00:00.572963", "end": "2020-09-29 15:19:56.091830", "item": "okd-bootstrap-01", "msg": "non-zero return code", "rc": 1, "start": "2020-09-29 15:19:55.518867", "stderr": "ERROR    Error: --disk size=20,readonly=false: Storage pool not found: no storage pool with matching name 'default'", "stderr_lines": ["ERROR    Error: --disk size=20,readonly=false: Storage pool not found: no storage pool with matching name 'default'"], "stdout": "", "stdout_lines": []}

**Comment by git4liluo** [comment]
solvedthnx

**Comment by ccamacho** [comment]
@git4liluo can you share what you did here to solve your issue?

**Comment by git4liluo** [comment]
I am new, tried some ways suggested here and there. I am not sure if this is the right way, seems working for me: 
1. virsh pool-list, I don't see default, I see images from the output;
2. virsh pool-destroy images
3. virsh pool-undefine images
4. then restart the deployment
5. virsh pool-define /dev/stdin << EOF
<pool type='dir'>
  <name>default</name>
  <target>
    <path>/var/lib/libvirt/images</path>
  </target>
</pool>
EOF
6. virsh pool-start default
7. virsh pool-autostart default
Many thanks for your created tool!
