### ISSUE TITLE
Installation shows "Error resolving host" but host can be resolved.

### ISSUE THREAD

**Issue by arturocp** [pubstack/pubstack.github.io#82]
Hi Carlos!

Thanks for sharing this project.

I set up a Centos8 machines for deploying OKD but I have an issue. I think it could be related to special characters in URL query string.

This is the error I get:

TASK [../../roles/kubeinit_okd : update packages] ***************************************************************************************************************************************************************
fatal: [hypervisor-01 -> 10.0.0.100]: FAILED! => {"changed": false, "msg": "Failed to download packages: Curl error (6): Couldn't resolve host name for http://mirrorlist.centos.org/?release=8-stream&arch=x86_64&repo=BaseOS&infra=genclo [Could not resolve host: mirrorlist.centos.org]", "results": []}**

PLAY RECAP ******************************************************************************************************************************************************************************************************
hypervisor-01              : ok=112  changed=25   unreachable=0    failed=1    skipped=28   rescued=0    ignored=4   

[root@okd kubeinit]# nslookup mirrorlist.centos.org
Server:		192.168.60.2
Address:	192.168.60.2#53

Non-authoritative answer:
Name:	mirrorlist.centos.org
Address: 35.180.43.213
Name:	mirrorlist.centos.org
Address: 85.236.43.108
Name:	mirrorlist.centos.org
Address: 67.219.148.138
Name:	mirrorlist.centos.org
Address: 147.75.83.237
Name:	mirrorlist.centos.org
Address: 147.75.69.225
Name:	mirrorlist.centos.org
Address: 18.225.36.18

**Comment by ccamacho** [comment]
Hello!

It looks like your ISP or network provider is blocking 1.1.1.1

Can you please look at https://github.com/Kubeinit/kubeinit/issues/198

Please feel free to ask any questions you have, and if you find any issues also feel free to raise issues in the project's repo (https://www.github.com/kubeinit/kubeinit). You can jump in and ask in the slack channel https://kubernetes.slack.com/archives/C01FKK19T0B Also, it would be awesome if you can star the project to catch up with updates and new features.

Thanks!

**Comment by arturocp** [comment]
Hello, Carlos!

Thanks for your fast response. Yesterday, I was trying some changes and I broke something, now appears:

TASK [../../roles/kubeinit_libvirt : Inject toor virt-customize assets] ********************************
fatal: [hypervisor-01 -> okd]: FAILED! => {"changed": false, "cmd": "virt-customize -a /var/lib/libvirt/images/okd-service-01.qcow2  --install python3  --run-command \"sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config\"  --run-command 'id -u toor &>/dev/null || /usr/sbin/useradd -u 1000 toor'  --run-command \"sed -i s/^SELINUX=.*$/SELINUX=disabled/g /etc/selinux/config\"  --ssh-inject toor:file:/home/toor/.ssh/id_rsa.pub  --ssh-inject root:file:/root/.ssh/authorized_keys  --run-command \"echo ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCfm4KMX0S7Gy/FG3bVq2CU3p0KLN3EAlU407nDm05o+SwxHkH+sTyqS85nY07YknVqfGbRyw7HOM6PfqkXmBV7WkjqJcLQZ2YZlrcWJp/QORmj+LHGyhBCOKbMxUJwHan1oeGaaQkpbmq2FqNSNVud12bmffL/j8aC5z0CubbvR6CTnWGl+8Ufo7o0UF/XfFFAx8VpyzdZoHKxH90tZMJ+TATiqERWPgb6YJuV3gK51ogXaABLMgcDaEL0AzMly4gAY2k67pwaNWe971q2zhoXyCDY8YQWA7c7/qEEPcblrjbKeAyYwtMrFekHbCVYMvObaWmu1ka47NvvTrMTrqnYeCEZ+bxkL1Xi2k243EwngEoaqzoaIAMl/UtGNZdwfGNQm4XekDjE6TX6v0bmLwKBvrVRVc3KYCopOVIDfBfOua7ZZ151/lK4hpGoBMcN6VdpXu8SabsZORq2oBpHIYj3+klYye/kavJW2hii3+ZH7XW0oJMSiyqAqX72GH5L9GEbRr6Lrj8IBHTs8NHk5y1pgCeDvXc4FghpnQkVkdO+JCxpKKdNqpcuSvGR57TCgN0xN1OEL98aVgavKLZSZQL03ZPsv1IzT9PK+WPGeqmmJbFermnC0pJ7g64s/dlw6+OJDmI6Gr/ns/M9w+TqBqsRBKzwgaIHgOxHCdifdU93Hw==  >> /root/.ssh/authorized_keys\"  --hostname okd-service-01.okdcluster.kubeinit.local  --copy-in /tmp/okd-service-01/ifcfg-eth0:/etc/sysconfig/network-scripts    --copy-in /tmp/okd-service-01/hosts.redhat.tmpl:/etc/cloud/templates  --copy-in /tmp/okd-service-01/cloud.cfg:/etc/cloud  --selinux-relabel --root-password password:xxxxxxxxxxxx\n", "delta": "0:00:00.844073", "end": "2021-03-27 09:41:02.968324", "msg": "non-zero return code", "rc": 1, "start": "2021-03-27 09:41:02.124251", "stderr": "virt-customize: error: libguestfs error: could not create appliance through \nlibvirt.\n\nTry running qemu directly without libvirt using this environment variable:\nexport LIBGUESTFS_BACKEND=direct\n\nOriginal error from libvirt: internal error: process exited while \nconnecting to monitor: 2021-03-27T14:41:02.327754Z qemu-kvm: error: failed \nto set MSR 0x48f to 0x7fefff00036dfb\nqemu-kvm: /builddir/build/BUILD/qemu-4.2.0/target/i386/kvm.c:2695: \nkvm_buf_set_msrs: Assertion `ret == cpu->kvm_msr_buf->nmsrs' failed. \n[code=1 int1=-1]\n\nIf reporting bugs, run virt-customize with debugging enabled and include \nthe complete output:\n\n  virt-customize -v -x [...]", "stderr_lines": ["virt-customize: error: libguestfs error: could not create appliance through ", "libvirt.", "", "Try running qemu directly without libvirt using this environment variable:", "export LIBGUESTFS_BACKEND=direct", "", "Original error from libvirt: internal error: process exited while ", "connecting to monitor: 2021-03-27T14:41:02.327754Z qemu-kvm: error: failed ", "to set MSR 0x48f to 0x7fefff00036dfb", "qemu-kvm: /builddir/build/BUILD/qemu-4.2.0/target/i386/kvm.c:2695: ", "kvm_buf_set_msrs: Assertion `ret == cpu->kvm_msr_buf->nmsrs' failed. ", "[code=1 int1=-1]", "", "If reporting bugs, run virt-customize with debugging enabled and include ", "the complete output:", "", "  virt-customize -v -x [...]"], "stdout": "[   0.0] Examining the guest ...", "stdout_lines": ["[   0.0] Examining the guest ..."]}


Thanks!

**Comment by ccamacho** [comment]
Yeah, that's something different, you need to share the changes you did to debug it. Please feel free to raise it in the project's GitHub site.
