### ISSUE TITLE
Getting error in task ../../roles/kubeinit_prepare : Create a minimal podman pod for the service containers running on service node VMs]

### ISSUE THREAD

**Issue by nbarodiya30** [pubstack/pubstack.github.io#84]
We are getting below error 

fatal: [localhost -> 10.0.0.100]: FAILED! => {"changed": false, "msg": "Can't create pod kubeinit-service-pod", "stderr": "time=\"2021-05-13T04:10:57Z\" level=error msg=\"Error freeing pod lock after failed creation: no such file or directory\"\nError: error adding Infra Container: Error initializing source docker://registry.access.redhat.com/ubi8/pause:latest: error pinging docker registry registry.access.redhat.com: Get \"https://registry.access.redhat.com/v2/\": dial tcp 23.212.252.56:443: i/o timeout\n", "stderr_lines": ["time=\"2021-05-13T04:10:57Z\" level=error msg=\"Error freeing pod lock after failed creation: no such file or directory\"", "Error: error adding Infra Container: Error initializing source docker://registry.access.redhat.com/ubi8/pause:latest: error pinging docker registry registry.access.redhat.com: Get \"https://registry.access.redhat.com/v2/\": dial tcp 23.212.252.56:443: i/o timeout"], "stdout": "", "stdout_lines": []}

Even we are not able to ping redhat.com from okd-services VM however able to ping other sites.

**Comment by ccamacho** [comment]
Hi! please create an issue in the project https://github.com/kubeinit/kubeinit so we can dig into it, also you can jump in the slack channel.
